{"timestamp":"2025-07-28T06:40:10.833334","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-28T06:40:10.835610","level":"info","event":"Filling up the DagBag from /home/azureuser/cloudfiles/code/users/abhishekbatti2001/llmfinetuning_stackoverflow/airflow_home/dags/preprocessing_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-28T06:40:10.927520Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-28T06:40:10.927761Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-28T06:40:10.928482Z","level":"info","event":"Current task name:run_preprocessing","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-28T06:40:10.928654Z","level":"info","event":"Dag name:stackoverflow_data_preprocessing","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-28T06:40:11.351598Z","level":"info","event":"[2025-07-28 06:40:11,351] INFO - Collecting paths","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-28T06:40:11.354718Z","level":"info","event":"[2025-07-28 06:40:11,352] INFO - paths Collected","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-28T06:40:11.354897Z","level":"info","event":"[2025-07-28 06:40:11,352] INFO - Creating spark app","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-28T06:40:13.116517Z","level":"error","event":"Error: LinkageError occurred while loading main class org.apache.spark.launcher.Main","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-28T06:40:13.117162Z","level":"error","event":"\tjava.lang.UnsupportedClassVersionError: org/apache/spark/launcher/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-28T06:40:13.126503Z","level":"error","event":"/anaconda/envs/azureml_py38/lib/python3.10/site-packages/pyspark/bin/spark-class: line 97: CMD: bad array subscript","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-28T06:40:13.170442Z","level":"error","event":"Traceback (most recent call last):","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-28T06:40:13.171221Z","level":"error","event":"  File \"/home/azureuser/cloudfiles/code/users/abhishekbatti2001/llmfinetuning_stackoverflow/airflow_home/src/preprocessing.py\", line 77, in <module>","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-28T06:40:13.184422Z","level":"error","event":"    preprocess_and_versiondata()","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-28T06:40:13.184712Z","level":"error","event":"  File \"/home/azureuser/cloudfiles/code/users/abhishekbatti2001/llmfinetuning_stackoverflow/airflow_home/src/preprocessing.py\", line 40, in preprocess_and_versiondata","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-28T06:40:13.184818Z","level":"error","event":"    spark = SparkSession.builder.appName(\"StackoverflowDataIngestion\").getOrCreate()","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-28T06:40:13.184895Z","level":"error","event":"  File \"/anaconda/envs/azureml_py38/lib/python3.10/site-packages/pyspark/sql/session.py\", line 556, in getOrCreate","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-28T06:40:13.184967Z","level":"error","event":"    sc = SparkContext.getOrCreate(sparkConf)","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-28T06:40:13.185037Z","level":"error","event":"  File \"/anaconda/envs/azureml_py38/lib/python3.10/site-packages/pyspark/core/context.py\", line 523, in getOrCreate","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-28T06:40:13.185106Z","level":"error","event":"    SparkContext(conf=conf or SparkConf())","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-28T06:40:13.185179Z","level":"error","event":"  File \"/anaconda/envs/azureml_py38/lib/python3.10/site-packages/pyspark/core/context.py\", line 205, in __init__","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-28T06:40:13.185264Z","level":"error","event":"    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-28T06:40:13.185337Z","level":"error","event":"  File \"/anaconda/envs/azureml_py38/lib/python3.10/site-packages/pyspark/core/context.py\", line 444, in _ensure_initialized","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-28T06:40:13.185410Z","level":"error","event":"    SparkContext._gateway = gateway or launch_gateway(conf)","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-28T06:40:13.185490Z","level":"error","event":"  File \"/anaconda/envs/azureml_py38/lib/python3.10/site-packages/pyspark/java_gateway.py\", line 111, in launch_gateway","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-28T06:40:13.185560Z","level":"error","event":"    raise PySparkRuntimeError(","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-28T06:40:13.185648Z","level":"error","event":"pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-28T06:40:13.273033","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"CalledProcessError","exc_value":"Command '['python', '/home/azureuser/cloudfiles/code/users/abhishekbatti2001/llmfinetuning_stackoverflow/airflow_home/src/preprocessing.py']' returned non-zero exit status 1.","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/anaconda/envs/azureml_py38/lib/python3.10/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":877,"name":"run"},{"filename":"/anaconda/envs/azureml_py38/lib/python3.10/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1164,"name":"_execute_task"},{"filename":"/anaconda/envs/azureml_py38/lib/python3.10/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/anaconda/envs/azureml_py38/lib/python3.10/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/anaconda/envs/azureml_py38/lib/python3.10/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/anaconda/envs/azureml_py38/lib/python3.10/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/home/azureuser/cloudfiles/code/users/abhishekbatti2001/llmfinetuning_stackoverflow/airflow_home/dags/preprocessing_dag.py","lineno":18,"name":"run_preprocessing_script"},{"filename":"/anaconda/envs/azureml_py38/lib/python3.10/subprocess.py","lineno":526,"name":"run"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-28T06:40:13.325016Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-28T06:40:13.325252Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-28T06:40:13.325356Z","level":"info","event":"Task:<Task(PythonOperator): run_preprocessing>","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-28T06:40:13.325428Z","level":"info","event":"Failure caused by Command '['python', '/home/azureuser/cloudfiles/code/users/abhishekbatti2001/llmfinetuning_stackoverflow/airflow_home/src/preprocessing.py']' returned non-zero exit status 1.","chan":"stdout","logger":"task"}
